default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>

development:
  <<: *default
  database: prompt_mint_development

test:
  <<: *default
  database: prompt_mint_test


production:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "prompt_mint_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_CACHE_DB", "prompt_mint_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_QUEUE_DB", "prompt_mint_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_CABLE_DB", "prompt_mint_cable") %>
    migrations_paths: db/cable_migrate
